### ISSUE TITLE
Wrong format of the sample code and miss azd download link in Readme

### ISSUE THREAD

**Issue by v-xuto** [Azure-Samples/openai-apim-lb#5]
1.
**Describe the issue:**
In [Sample Code Readme](https://github.com/Azure-Samples/openai-apim-lb/blob/main/docs/sample-code.md#sample-code), the sample code is not in the correct format.
![image](https://github.com/Azure-Samples/openai-apim-lb/assets/57166602/9afc6f0d-c0b0-42eb-815c-5a6b2ed0d0a4)

**Expected behavior:**
The sample code is well-formed and looks like this:
![image](https://github.com/Azure-Samples/openai-apim-lb/assets/57166602/a2c8de01-4e76-4b5e-add2-6f1cc2c9b039)

2.
**Describe the issue:**
Miss [Azure Developer CLI](https://aka.ms/azd-install) download link in [readme](https://github.com/Azure-Samples/openai-apim-lb/blob/main/docs/azd-setup.md).
![image](https://github.com/Azure-Samples/openai-apim-lb/assets/57166602/767a466a-d124-4741-ba52-a9a44fa7899d)

**Expected behavior:**
Readme `azd-setup.md` contains [Azure Developer CLI](https://aka.ms/azd-install) download link.

@codebytes  and @hemarina for notification

**Comment by codebytes** [comment]
This issue should be resolved now
